# A sql script to drop all of the tables added by this program.

DROP TABLE IF EXISTS ExQuestions;
DROP TABLE IF EXISTS AttAnswers;
DROP TABLE IF EXISTS Attempt;
DROP TABLE IF EXISTS Answer;
DROP TABLE IF EXISTS Parameters;
DROP TABLE IF EXISTS Question;
DROP TABLE IF EXISTS CourseTopic;
DROP TABLE IF EXISTS EnrolledIn;
DROP TABLE IF EXISTS TAFor;
DROP TABLE IF EXISTS Exercise;
DROP TABLE IF EXISTS Topic;
DROP TABLE IF EXISTS Course;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS Instructor;
DROP TABLE IF EXISTS Graduate;
DROP TABLE IF EXISTS User;